config/routes.rb
Rails.application.routes.draw do
  resources :time_offs
  resources :attendances, only: [:index, :show] do
    get 'new_comment', on: :collection
    post 'create_comment', on: :collection
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show] do
    get 'log_time_in', on: :collection
    get 'log_time_out', on: :collection
  end
  root to: "attendances#index"
end

app/models/time_off.rb
class TimeOff < ApplicationRecord
  belongs_to :user
end

app/controllers/time_offs_controller.rb
class TimeOffsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_time_off, only: [:show, :edit, :update, :destroy]

  # GET /time_offs
  # GET /time_offs.json
  def index
    if current_user.admin?  
      @time_offs = TimeOff.all
    else
      @time_offs = current_user.time_offs
    end
  end

  # GET /time_offs/1
  # GET /time_offs/1.json
  def show
    @time_offs = TimeOff.find(params[:id])
    unless @time_offs.user == current_user
      redirect_to time_offs_url, notice: "You're not authorized to check timeoffs of #{@atime_off.user.first_name} #{@time_off.user.last_name}."
    end
  end

  # GET /time_offs/new
  def new
    @time_off = TimeOff.new
  end

  # GET /time_offs/1/edit
  def edit
  end

  # POST /time_offs
  # POST /time_offs.json
  def create
    @time_off = TimeOff.new(time_off_params)
    


    respond_to do |format|
      if @time_off.save
        LeaveMailer.leave_email(@time_off.user).deliver

        format.html { redirect_to @time_off, notice: 'Time off was successfully created.' }
       
        format.json { render :show, status: :created, location: @time_off }
      else
        format.html { render :new }
        format.json { render json: @time_off.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_offs/1
  # PATCH/PUT /time_offs/1.json
  def update
    respond_to do |format|
      if @time_off.update(time_off_params)
        format.html { redirect_to @time_off, notice: 'Time off was successfully updated.' }
        format.json { render :show, status: :ok, location: @time_off }
      else
        format.html { render :edit }
        format.json { render json: @time_off.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_offs/1
  # DELETE /time_offs/1.json
  def destroy
    @time_off.destroy
    respond_to do |format|
      format.html { redirect_to time_offs_url, notice: 'Time off was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_off
      @time_off = TimeOff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def time_off_params
      params.require(:time_off).permit(:from_date, :to_date, :note).merge(user_id: current_user.id)
    end
  end

app/helpers/time_offs_helper.rb
module TimeOffsHelper
end

app/views/time_offs/_form.html.erb
<%= form_with(model: time_off, local: true) do |form| %>
  <% if time_off.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(time_off.errors.count, "error") %> prohibited this time_off from being saved:</h2>

      <ul>
      <% time_off.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :from_date %>
    <%= form.datetime_select :from_date %>
  </div>

  <div class="field">
    <%= form.label :to_date %>
    <%= form.datetime_select :to_date %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_field :note %>
  </div>

  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/time_offs/edit.html.erb
<h1>Editing Time Off</h1>

<%= render 'form', time_off: @time_off %>

<%= link_to 'Show', @time_off %> |
<%= link_to 'Back', time_offs_path %>

app/views/time_offs/index.html.erb
<p id="notice"><%= notice %></p>
<center>
<h1>Time Offs</h1>


<table>
  <thead>
    <tr>
      <th>From date</th>
      <th>To date</th>
      <th>Note</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @time_offs.each do |time_off| %>
      <tr>
         <% if current_user.admin? %>
          <td><%= "#{time_off.user.first_name} #{time_off.user.last_name}" %></td>
        <% end %>
        <td><%= time_off.from_date %></td>
        <td><%= time_off.to_date %></td>
        <td><%= time_off.note %></td>
       
        <td><%= link_to 'Show', time_off %></td>
        <td><%= link_to 'Edit', edit_time_off_path(time_off) %></td>
        <td><%= link_to 'Destroy', time_off, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</center>

<center>
<%= link_to 'New Time Off', new_time_off_path %>
</center>

app/views/time_offs/new.html.erb
<h1>New Time Off</h1>

<%= render 'form', time_off: @time_off %>

<%= link_to 'Back', time_offs_path %>

app/views/time_offs/show.html.erb
<p id="notice"><%= notice %></p>


<center>
<p>
  <strong>From date:</strong>
  <%= @time_off.from_date %>
</p>
</centre>

<center>
<p>
  <strong>To date:</strong>
  <%= @time_off.to_date %>
</p>
</center>

<center>

<p>
  <strong>Note:</strong>
  <%= @time_off.note %>
</p>

</center>

<center>
<p>
  <strong>User:</strong>
  <%= "#{@time_off.user.first_name} #{@time_off.user.last_name}" %>
</p>

</center>

<%= link_to 'Edit', edit_time_off_path(@time_off) %> |
<%= link_to 'Back', time_offs_path %>