config/routes.rb
Rails.application.routes.draw do
  resources :time_offs
  resources :attendances, only: [:index, :show] do
    get 'new_comment', on: :collection
    post 'create_comment', on: :collection
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show] do
    get 'log_time_in', on: :collection
    get 'log_time_out', on: :collection
  end
  root to: "attendances#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :trackable
  enum role: [:employee, :admin]
  after_initialize :set_default_role_status, :if => :new_record?

  def set_default_role_status
    self.role ||= :employee
    self.status ||= true
  end
  has_many :attendances
  has_many :time_offs
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = current_user
  end

  def log_time_in
    attendance = current_user.attendances.create(time_in: DateTime.now)
    redirect_to attendances_url, notice: "You've successfully started your day at Work. Rock it!"
  end

  def log_time_out
    attendance = current_user.attendances.where(time_in: Date.today.all_day).last
    if attendance.blank?
      redirect_to attendances_url, notice: "Please log you're time_in first!"
    else
      attendance.update_attributes(time_out: DateTime.now)
      redirect_to attendances_url, notice: "Thanks for your contribution! Take Rest! See you soon!"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/menu/_login_items.html.erb
<% if user_signed_in? %>
  <li class="nav-item">
  <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link") %>
  </li>
<% else %>
  <li class="nav-item">
  <%= link_to('Login', new_user_session_path, class: "nav-link")  %>
  </li>
<% end %>

app/views/users/menu/_navbar.html.erb
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <!-- <li class="nav-item">
      <%#= link_to('Companies', companies_path, class: "nav-link") %>
    </li> -->
  <% end %>
  <li class="nav-item">
  <%= link_to('Attendance', attendances_path, class: "nav-link") %>
  </li>
  <li class="nav-item">
  <%= link_to('Users', users_path, class: "nav-link") %>
  </li>
  <li class="nav-item">
  <%= link_to('Time_offs' , time_offs_path, class: "nav-link") %>
  </li>
  <% end %>

app/views/users/menu/_registration_items.html.erb
<% if user_signed_in? %>
  <li class="nav-item">
  <%= link_to('Edit profile', edit_user_registration_path, class: "nav-link") %>
  </li>
<% else %>
  <li class="nav-item">
  <%= link_to('Register', new_user_registration_path, class: "nav-link")  %>
  </li>
<% end %>