config/routes.rb
Rails.application.routes.draw do
  resources :time_offs
  resources :attendances, only: [:index, :show] do
    get 'new_comment', on: :collection
    post 'create_comment', on: :collection
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show] do
    get 'log_time_in', on: :collection
    get 'log_time_out', on: :collection
  end
  root to: "attendances#index"
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  paginates_per 10
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_attendance, only: [:show, :edit, :update, :destroy]

  # GET /attendances
  # GET /attendances.json
  def index

    if current_user.admin?
      @attendances = Attendance.all
    else
      @attendances = current_user.attendances
    end

    @attendances = @attendances.order(created_at: :desc).page params[:page]

    @time_in_present = current_user.attendances.where(time_in: Date.today.all_day).present?
    @time_out_present = current_user.attendances.where(time_out: Date.today.all_day).present?

  end

  # GET /attendances/1
  # GET /attendances/1.json
  def show
    @attendance = Attendance.find(params[:id])
    unless @attendance.user == current_user
      redirect_to attendances_url, notice: "You're not authorized to check attendance of #{@attendance.user.first_name} #{@attendance.user.last_name}."
    end
  end

  # GET /attendances/new
  def new
    @attendance = Attendance.new
  end

  # GET /attendances/1/edit
  def edit
  end

  # POST /attendances
  # POST /attendances.json
  def create
    @attendance = Attendance.new(attendance_params)

    respond_to do |format|
      if @attendance.save
        format.html { redirect_to @attendance, notice: 'Attendance was successfully created.' }
        format.json { render :show, status: :created, location: @attendance }
      else
        format.html { render :new }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendances/1
  # PATCH/PUT /attendances/1.json
  def update
    respond_to do |format|
      if @attendance.update(attendance_params)
        format.html { redirect_to @attendance, notice: 'Attendance was successfully updated.' }
        format.json { render :show, status: :ok, location: @attendance }
      else
        format.html { render :edit }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendances/1
  # DELETE /attendances/1.json
  def destroy
    @attendance.destroy
    respond_to do |format|
      format.html { redirect_to attendances_url, notice: 'Attendance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def new_comment
    @attendance = current_user.attendances.where(time_in: Date.today.all_day).last
    if @attendance.blank?
      redirect_to attendances_url, notice: "Please log you're time_in first!"
    end
  end

  def create_comment
    attendance = current_user.attendances.where(time_in: Date.today.all_day).last
    if attendance.blank?
      redirect_to attendances_url, notice: "Please log you're time_in first!"
    else
      attendance.update_attributes(time_out: DateTime.now, comments: "#{params[:comments1]}\n#{params[:comments2]}\n#{params[:comments3]}")
      redirect_to attendances_url, notice: "Thanks for your contribution! Take Rest! See you soon!"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendance
      @attendance = Attendance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attendance_params
      params.fetch(:attendance, {})
    end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/views/attendances/_form.html.erb
<%= form_with url: create_comment_attendances_path, html: {style: "width: 100%;max-width: 330px;padding: 15px;margin: auto;"} do |form| %>
  <% if attendance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>

      <ul>
      <% attendance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "What did you do today?" %>
    <%= form.text_area :comments1, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label "What will you do tomorrow?" %>
    <%= form.text_area :comments2, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label "Are there any impediments in your way?" %>
    <%= form.text_area :comments3, class: "form-control" %>
  </div>

  <div class="actions" style="text-align: center;padding: 10px;">
    <%= form.submit "Log Time-Out", class: "btn btn-lg btn-danger" %>
  </div>
<% end %>

app/views/attendances/_index.html.erb
<table class="table table-hover">
  <thead class="thead-light">
    <tr>
      <% if current_user.admin? %>
        <th>User</th>
      <% end %>
      <th>Date</th>
      <th>Time in</th>
      <th>Time out</th>
      <th>Comments</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @attendances.each do |attendance| %>
      <tr>
        <% if current_user.admin? %>
          <td><%= "#{attendance.user.first_name} #{attendance.user.last_name}" %></td>
        <% end %>
        <td><%= attendance.time_in&.strftime("%v") %></td>
        <td><%= attendance.time_in&.strftime("%r") %></td>
        <td><%= attendance.time_out&.strftime("%r") %></td>
        <td class="wrappable"><%= attendance.comments %></td>
        <td><%= link_to 'Show', attendance %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="container">
  <%= link_to_previous_page @attendances, '❮ Previous', class: "btn btn-primary float-left" %>
  <%= link_to_next_page @attendances, 'Next ❯', class: "btn btn-primary float-right" %>
</div>

app/views/attendances/edit.html.erb
<h1>Editing Attendance</h1>

<%= render 'form', attendance: @attendance %>

<%= link_to 'Show', @attendance %> |
<%= link_to 'Back', attendances_path %>

app/views/attendances/index.html.erb
<style media="screen">
  .container {
    text-align: center;
  }
  .wrappable {
    overflow: hidden;
    max-width: 600px;
    word-wrap: break-word;
    text-align: justify;
  }
  .table th, .table td {
    vertical-align: middle;
  }
</style>
<% unless notice.blank? %>
  <div class="alert alert-info alert-dismissible">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <%= notice %>
  </div>
<% end %>


<center>
  <h2>Attendances</h2>
  <% unless @time_in_present %>
    <%= link_to 'Log Time-In', log_time_in_users_path, class: "btn btn-danger mb-3" %>
  <% else %>
    <%= link_to('Log Time-Out', new_comment_attendances_path, class: "btn btn-danger mb-3") unless @time_out_present %>
  <% end %>
</center>


<div class="container">
  <div class="row">
      <%= render "index" %>
  </div>
</div>

app/views/attendances/new_comment.html.erb
<%= render 'form', attendance: @attendance %>

<%#= link_to 'Back', attendances_path %>

app/views/attendances/show.html.erb
<% unless notice.blank? %>
  <div class="alert alert-info alert-dismissible">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <%= notice %>
  </div>
<% end %>

<p>
  <strong>User:</strong>
  <%= "#{@attendance.user.first_name} #{@attendance.user.last_name}" %>
</p>

<p>
  <strong>Time in:</strong>
  <%= @attendance.time_in %>
</p>

<p>
  <strong>Time out:</strong>
  <%= @attendance.time_out %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @attendance.comments %>
</p>

<%= link_to 'Back', attendances_path %>